# Generated by Django 2.2.15 on 2020-08-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_forecastweather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForecastWeather',
        ),
    ]
